apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-webpage
  template:
    metadata:
      labels:
        app: gke-webpage
    spec:
      containers:
        - name: gke-webpage
          image: us-east1-docker.pkg.dev/upgradlabs-1740997931739/vivekarfirst/gke-webpage:latest
          ports:
            - containerPort: 80

